name: make8bitart
version: master
summary: an in-browser canvas tool which is great fun!
description: |
  web-based pixel art application that's super fun and easy to use!

grade: devel
confinement: strict

apps:
  server:
    command: sh -c \"cd $SNAP/lib/node_modules/make8bitart && http-server -a localhost -p 8080\"
    plugs: [network-bind]
    daemon: simple

parts:
  make8bitart:
    source:
    plugin: nodejs
    node-packages: [http-server]
